name: Publish to PyPI on Tag

on:
  push:
    tags:
      - "v*"   # e.g. v0.1.0, v1.2.3, etc.

permissions:
  contents: read

jobs:
  build-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Update pyproject.toml version
        run: |
          # Remove leading 'v' from the tag name (e.g., "v1.2.3" -> "1.2.3")
          VERSION="${GITHUB_REF_NAME#v}"

          # Install dependencies needed to parse toml
          python -m pip install --upgrade pip
          python -m pip install toml

          # Update the version in pyproject.toml (single-line Python command)
          python -c "import toml; p='pyproject.toml'; d=toml.load(p); d['project']['version']='$VERSION'; toml.dump(d, open(p,'w'))"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  publish-dist:
    runs-on: ubuntu-latest
    needs: [build-dist]
    permissions:
      id-token: write  # Required for OIDC-based publishing to PyPI
      contents: read

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
