name: Release on Tag

on:
  push:
    tags:
      - 'v*'  # Triggers on any tag starting with "v", e.g. v1.0.0

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: |
            **Woohoo!** You've stumbled upon the latest and greatest release!
            Imagine confetti popping, dancing unicorns, and flying tacos—
            that's how excited I am to share this version.

            Enjoy this joyful update, and remember:
            - Smiles are mandatory
            - Party hats are optional
            - Dancing is highly encouraged

            Have fun and celebrate! 🎉
          draft: false
          prerelease: false
